<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

    <!-- Compile Test Plugin Assembly (QikFunnyFunctions) and copy it into output Plugins folder. -->
    <Target Name="BuildAndCopyTestPlugin" BeforeTargets="BeforeBuild">
        <Exec Command="dotnet build $(ProjectDir)..\QikFunnyFunctions\QikFunnyFunctions.csproj" />
        <Copy SourceFiles="$(ProjectDir)..\QikFunnyFunctions\bin\Debug\net7.0\QikFunnyFunctions.dll" DestinationFolder="$(OutDir)\Plugins" />
    </Target>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="6.7.0" />
    <PackageReference Include="Moq" Version="4.18.2" />
    <PackageReference Include="NUnit" Version="3.13.3" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.2.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\QikConsole\QikConsole.csproj" />
  </ItemGroup>

  <ItemGroup>
      <Content Include="Files\projects.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
